Laba 4-5
jhlfrfufyfn/database_companies pull request #1
Opened 2020-09-30 19:37 UTC by jhlfrfufyfn

2020-10-03 15:51 UTC, VeronikaYastr requested changes

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Company.java
> +    String name;
Лучше сделать поля private

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Query.java
> +    static List<Company> findByActType(String catLine, List<Company> records) {
Что такое catLine?)
String activityType как вариант)

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Query.java
> +    static List<Company> findByEmplNumber(int n1, int n2, List<Company> records) {
Тоже не совсем понятно, что такое n1, n2

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Query.java
> +    static List<Company> findByFDate(Date date1, Date date2, List<Company> records) {
startDate, endDate

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Company.java
> +        name = aData[0];
Проверка на размер массива не помешала бы

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +                System.out.println("Enter the query number(enter 0 if you want to finish the program): ");
Хорошо было бы конечно вывести меню. Какие запросы на какую цифру)

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +                    case 1:
Можно создать enum с типами запросов
Типа RequestType
REQUEST_BY_SHORT_NAME, REQUEST_BY_NAME и т.д

2020-10-03 15:51 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +                        int n1 = Integer.parseInt(nums[0]);
Тоже проверить на то, что в массиве два элемента

2020-10-04 00:11 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                    case 1:
каким образом?

метка в case должна быть 'compile-time constant', то бишь например геттером вернуть поле enum'a и пихнуть его в case не получится

можно case записать с помощью непосредственно имени элемента enum'a, но тогда в Main придется перед switch писать еще ифов для проставления соответствия номера запроса элементу enum'a(то же самое что и сейчас имхо)

или можно сделать не enum, а абстрактный класс с константами(их можно будет пихать в switch)

или есть третий вариант который я не вижу

как сделать лучше?

2020-10-04 00:26 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                    case 1:
грубо говоря если enum выглядит так:
https://paste.ofcode.org/ZggBv27vHEY6gmttvS6Ybx

то этот код не компилируется
https://paste.ofcode.org/ExgZyrKzPBTEMB6aERnYR7

2020-10-04 00:28 UTC, jhlfrfufyfn commented on src/com/bsu/Company.java
> +    String name;
done

2020-10-04 00:28 UTC, jhlfrfufyfn commented on src/com/bsu/Query.java
> +    static List<Company> findByActType(String catLine, List<Company> records) {
done

2020-10-04 00:28 UTC, jhlfrfufyfn commented on src/com/bsu/Query.java
> +    static List<Company> findByEmplNumber(int n1, int n2, List<Company> records) {
done

2020-10-04 00:29 UTC, jhlfrfufyfn commented on src/com/bsu/Query.java
> +    static List<Company> findByFDate(Date date1, Date date2, List<Company> records) {
done

2020-10-04 00:29 UTC, jhlfrfufyfn commented on src/com/bsu/Company.java
> +        name = aData[0];
done

2020-10-04 00:29 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                        int n1 = Integer.parseInt(nums[0]);
done

2020-10-04 10:07 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +                    case 1:
https://paste.ofcode.org/uUFM23Mg4NLtQbEhu7WHY8 - можно так

2020-10-04 10:10 UTC, VeronikaYastr requested changes

2020-10-04 10:10 UTC, VeronikaYastr commented on src/com/bsu/Company.java
> +            throw new IOException("Error: wrong number of fields in the data");
Я бы не сказала, что это IOException. Это скорее неверный аргумент или параметр. Но это не ошибка чтения/записи

2020-10-04 10:10 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +                            throw new IOException("Error: wrong number of numbers entered in query 5");
Аналогично, это неверный аргумент, но не IOException

2020-10-04 10:11 UTC, VeronikaYastr commented on src/com/bsu/Company.java
> +    String name;
Можно нажимать кнопочку "Resolve conversation", если исправляешь. Чтобы лишние диалоги не висели тут, а осталось только незакрытое

2020-10-05 13:11 UTC, jhlfrfufyfn commented on src/com/bsu/Company.java
> +            throw new IOException("Error: wrong number of fields in the data");
done

2020-10-05 13:11 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                            throw new IOException("Error: wrong number of numbers entered in query 5");
done

2020-10-05 13:36 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                    case 1:
done

2020-10-05 13:50 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                System.out.println("Enter the query number(enter 0 if you want to finish the program): ");
done

2020-10-05 14:52 UTC, VeronikaYastr commented on src/com/bsu/Company.java
> +        name = aData[0];
Кстати, здесь можно вызвать this(aData[0], aData[1]...); (вызовет конструктор с параметрами)

2020-10-05 15:01 UTC, VeronikaYastr requested changes

2020-10-07 19:18 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                q = Integer.parseInt(cin.nextLine());
https://stackoverflow.com/questions/13102045/scanner-is-skipping-nextline-after-using-next-or-nextfoo

у меня была такая проблема, и мне показалось что так лучше ее решать(можно было еще после cin.nextInt() написать cin.nextLine() чтобы съесть '\n',)

2020-10-07 20:07 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +                q = Integer.parseInt(cin.nextLine());
Ааа, тогда да)

2020-10-07 20:34 UTC, jhlfrfufyfn commented on src/com/bsu/Company.java
> +        name = aData[0];
done

2020-10-07 20:34 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                        LOGGER.fine(queryInfo + ", companies found: "
done

2020-10-07 20:34 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +        try (FileWriter fout = new FileWriter(CSV_OUT_FILENAME)) {
done

2020-10-07 21:29 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +                        fout.write("Companies found: " + System.lineSeparator());
enod

2020-10-08 08:13 UTC, merged