assignment 6 is done
jhlfrfufyfn/database_companies pull request #2
Opened 2020-11-07 14:28 UTC by jhlfrfufyfn

I hate this select query so much

2020-11-26 05:14 UTC, VeronikaYastr requested changes

2020-12-02 20:28 UTC, jhlfrfufyfn commented on src/com/bsu/Company.java
> +        name(0), shortName(1), actualizationDate(2), address(3),
done

2020-12-02 20:28 UTC, jhlfrfufyfn commented on src/com/bsu/Logic_Parser.java
> +    static boolean ParseStringExpression(String[] words, String correctName, String specificName) {
done

2020-12-02 20:28 UTC, jhlfrfufyfn commented on src/com/bsu/Logic_Parser.java
> +    static boolean ParseNumberExpression(String[] words, int correctNumber, String specificName) {
done

2020-12-25 10:46 UTC, merged